Drop before_install steps
This makes Ruby 1.9 unhappy:

ERROR:  Error installing rubygems-update:
        There are no versions of rubygems-update (= 3.1.3) compatible
        with your Ruby & RubyGems rubygems-update requires Ruby version
        >= 2.3.0. The current ruby version is 1.9.1.

I don't think it's required.